/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateTasksIndexRouteImport } from './routes/_private/_tasks/index'
import { Route as PrivateTasksTasksCreateRouteImport } from './routes/_private/_tasks/tasks/create'
import { Route as PrivateTasksTasksTaskIdRouteImport } from './routes/_private/_tasks/tasks/$taskId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateTasksIndexRoute = PrivateTasksIndexRouteImport.update({
  id: '/_tasks/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTasksTasksCreateRoute = PrivateTasksTasksCreateRouteImport.update({
  id: '/_tasks/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTasksTasksTaskIdRoute = PrivateTasksTasksTaskIdRouteImport.update({
  id: '/_tasks/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PrivateTasksIndexRoute
  '/tasks/$taskId': typeof PrivateTasksTasksTaskIdRoute
  '/tasks/create': typeof PrivateTasksTasksCreateRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PrivateTasksIndexRoute
  '/tasks/$taskId': typeof PrivateTasksTasksTaskIdRoute
  '/tasks/create': typeof PrivateTasksTasksCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_private/_tasks/': typeof PrivateTasksIndexRoute
  '/_private/_tasks/tasks/$taskId': typeof PrivateTasksTasksTaskIdRoute
  '/_private/_tasks/tasks/create': typeof PrivateTasksTasksCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/' | '/tasks/$taskId' | '/tasks/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/tasks/$taskId' | '/tasks/create'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_private/_tasks/'
    | '/_private/_tasks/tasks/$taskId'
    | '/_private/_tasks/tasks/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/_tasks/': {
      id: '/_private/_tasks/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateTasksIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_tasks/tasks/create': {
      id: '/_private/_tasks/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof PrivateTasksTasksCreateRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_tasks/tasks/$taskId': {
      id: '/_private/_tasks/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof PrivateTasksTasksTaskIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateTasksIndexRoute: typeof PrivateTasksIndexRoute
  PrivateTasksTasksTaskIdRoute: typeof PrivateTasksTasksTaskIdRoute
  PrivateTasksTasksCreateRoute: typeof PrivateTasksTasksCreateRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateTasksIndexRoute: PrivateTasksIndexRoute,
  PrivateTasksTasksTaskIdRoute: PrivateTasksTasksTaskIdRoute,
  PrivateTasksTasksCreateRoute: PrivateTasksTasksCreateRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
